name: linguacafe

networks:
    linguacafe:
        driver: bridge

services:
    webserver:
        image: ghcr.io/simjanos-dev/linguacafe-webserver:${VERSION:-latest}
        container_name: linguacafe-webserver
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./storage:/var/www/html/storage
            - ./docker/supervisor-horizon.conf:/etc/supervisor/conf.d/horizon.conf
            - ./docker/supervisor-websockets.conf:/etc/supervisor/conf.d/websockets.conf
        environment:
            DB_DATABASE: ${DB_DATABASE:-linguacafe}
            DB_USERNAME: ${DB_USERNAME:-linguacafe}
            DB_PASSWORD: ${DB_PASSWORD:-linguacafe}
            DB_HOST: ${DB_HOST:-linguacafe-database}
            DB_PORT: ${DB_PORT:-3306}
            BACKUP_INTERVAL: "59 23 * * *"
            MAX_SAVED_BACKUPS: 14
        ports:
            - "6001:6001"
            - "${PORT:-9191}:80"
        networks:
            - linguacafe
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${DB_ROOT_PASSWORD:-linguacafe}']
            interval: 10s
            timeout: 5s
            retries: 10
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-linguacafe}
            MYSQL_USER: ${DB_USERNAME:-linguacafe}
            MYSQL_PASSWORD: ${DB_PASSWORD:-linguacafe}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-linguacafe}
            SERVICE_NAME: linguacafe
        command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
        networks:
            - linguacafe
    redis:
        image: redis:7.2-alpine
        container_name: linguacafe-redis
        restart: unless-stopped
        volumes:
            - ./cache:/data
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: linguacafe
            REDIS_PORT: 6379
            REDIS_DATABASES: 16
        networks:
            - linguacafe
    python:
        container_name: linguacafe-python-service
        command: "python3 /app/tokenizer.py"
        restart: unless-stopped
        tty: true
        image: ghcr.io/simjanos-dev/linguacafe-python-service:${VERSION:-latest}
        environment:
            PYTHONPATH: "/var/www/html/storage/app/model"
        volumes:
            - ./storage:/var/www/html/storage
        networks:
            - linguacafe
        platform: ${PLATFORM:-}
